FROM node:alpine as build

COPY ./ /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

RUN npm ci --silent
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]