version: "3.7"

services:
  mass-vue:
    container_name: mass-vue
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks: 
      - traefik_default
    labels:
      - traefik.enable=true

networks:
  traefik_default:
    external: true