version: "3.7"

services: 
  mass-vue:
    container_name: mass-vue
    user: node
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: "${APP_PORT}"
    volumes:
      - .:/app
    networks: 
      - traefik_default
    labels:
      - traefik.enable=true
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=${TRAEFIK_PROTOCOL:-https}"

networks:
  traefik_default:
    external: true