name: Build App

on:  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          check-latest: true
      - run: cp .env.example .env
      - run: npm ci
      - run: tsc --project tsconfig.json --noEmit
      - run: npm run build